[tool.poetry]
name = "ia-osu-player_cuda"
version = "0.1.0"
description = ""
authors = ["elroche <elroche@ensc.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "^1.23.2"
pandas = "^2.1.1"
matplotlib = "^3.8.0"
seaborn = "^0.12.2"
scikit-learn = "^1.3.1"
torch = { version = "^2.0.0 , !=2.0.1", source = "torch-cu117" }
torchvision = { version = "^0.15.1", source = "torch-cu117" }

[tool.poetry.group.dev.dependencies]
jupytext = "^1.15.2"
notebook = "^7.0.4"
ipykernel = "^6.25.2"
jupyter = "^1.0.0"
pylint = "^2.17.6"

[[tool.poetry.source]]
name = "torch-cu117"
url = "https://download.pytorch.org/whl/cu117"
priority = "supplemental"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.jupytext]
formats = "notebooks///ipynb,scripts///py:percent"

## To NOT install cuda use the following command : poetry install --without torch-cu117 
## If willing to use torch cpu , use after : pip install torch