[tool.poetry]
name = "ia-osu-player"
version = "0.1.0"
description = ""
authors = ["Elea Roche , Quentin Perret"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytorch = "^1.0.2"
numpy = "^1.24.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
