[tool.poetry]
name = "ia-osu-player_cpu"
version = "0.1.0"
description = "Projet réalisé par les étudiants de l'ENSC [ROCHE Eléa](https://github.com/elroche) et [PERRET Quentin](https://github.com/QuentinPerret)."
authors = ["elroche <elroche@ensc.fr>" , qperret <quentinprrt33@gmail.com>]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "^1.23.2"
matplotlib = "^3.8.0"
opencv-python = "^4.7.0"
pyautogui = "^0.9.54"
pytesseract = "^0.3.10"
tesseract = "^0.1.3"

torch = { version = "^2.0.0 , !=2.0.1", source = "torch-cpu" }
torchvision = { version = "*", source = "torch-cpu" }

[tool.poetry.group.dev.dependencies]
jupytext = "^1.15.2"
notebook = "^7.0.4"
ipykernel = "^6.25.2"
jupyter = "^1.0.0"
pylint = "^2.17.6"

[[tool.poetry.source]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "supplemental"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.jupytext]
formats = "notebooks///ipynb,scripts///py:percent"
